
# # first external source to load snippets
# [[sources]] # list of sources to load
# name = "source1"                        # optional name shown on snippet description 
# git = "https://example.com/source1.git" # git repo with snippets collections

# [[sources.paths]] # explicit list of paths to load on current source
# scope = [
#   "scope1",
#   "scope2",
# ] # optional scopes (language id) for current snippets
# path = "path-in-repo/snippets1.json" # where snippet file or dir located in repo

# [[sources.paths]]
# scope = ["scope3"]
# path = "path-in-repo/snippets2.json"

# # next external source to load snippets
# [[sources]]
# name = "source2"
# git = "https://example.com/source2.git"

# [[sources.paths]]
# scope = ["scope1"]
# path = "path-in-repo-of-source2/snippets1.json"


[[sources]]
name = "friendly-snippets"
git = "https://github.com/rafamadriz/friendly-snippets.git"

[[sources.paths]]
scope = ["python"]
path = "snippets/python/python.json"

[[sources.paths]]
scope = ["rust"]
path = "snippets/rust/rust.json"

[[sources.paths]]
scope = ["c"]
path = "snippets/c/c.json"

[[sources.paths]]
scope = ["markdown"]
path = "snippets/markdown.json"

[[sources.paths]]
scope = ["java"]
path = "snippets/java/java.json"

[[sources.paths]]
scope = ["kotlin"]
path = "snippets/kotlin/kotlin.json"

[[sources.paths]]
scope = ["c-sharp"]
path = "snippets/csharp/csharp.json"

[[sources.paths]]
scope = ["csharp"]
path = "snippets/csharp/csharp.json"

[[sources.paths]]
scope = ["zig"]
path = "snippets/zig.json"

[[sources.paths]]
scope = ["html"]
path = "snippets/html.json"

[[sources.paths]]
scope = ["cmake"]
path = "snippets/cmake.json"

[[sources.paths]]
scope = ["css"]
path = "snippets/css.json"


[[sources.paths]]
scope = ["javascript"]
path = "snippets/javascript/javascript.json"


[[sources.paths]]
scope = ["dart"]
path = "snippets/dart.json"

[[sources.paths]]
scope = ["go"]
path = "snippets/go.json"


[[sources.paths]]
scope = ["javascriptreact"]
path = "snippets/javascript/.json"


[[sources.paths]]
# scope = ["typescript", "ts"]
scope = ["typescript"]
path = "snippets/javascript/typescript.json"
