# Author: Rosé Pine <hi@rosepinetheme.com>
# Upstream: https://github.com/rose-pine/helix
# Contributing:
#   Please submit changes to https://github.com/rose-pine/helix.
#   The Rosé Pine team will update Helix, including you as a co-author.

# "ui.background" = { bg = "" }
# "ui.background.separator" = { bg = "" }
# "ui.statusline" = { fg = "subtle", bg = "" }

"ui.cursor" = { fg = "text", bg = "highlight_high" }
# "ui.cursor.select" = {}
"ui.cursor.match" = { fg = "text", bg = "highlight_med" }
"ui.cursor.primary" = { fg = "text", bg = "muted" }

# "ui.gutter" = {}
# "ui.gutter.selected" = {}

"ui.linenr" = { fg = "muted" }
"ui.linenr.selected" = { fg = "text" }

# "ui.bufferline" = { fg = "muted", bg = "base" }

"ui.bufferline.active" = { fg = "text", bg = "overlay" }

"ui.statusline.inactive" = { fg = "muted", bg = "surface" }
# "ui.statusline.inactive" = { fg = "muted", bg = "surface" }
"ui.statusline.normal" = { fg = "rose", bg = "rose_10" }
"ui.statusline.insert" = { fg = "foam", bg = "foam_10" }
"ui.statusline.select" = { fg = "iris", bg = "iris_10" }
# "ui.statusline.separator" = {}

"ui.popup" = { bg = "surface" }
"ui.popup.info" = { bg = "surface" }

"ui.window" = { fg = "overlay", bg = "base" }
"ui.help" = { fg = "subtle", bg = "overlay" }

"ui.text" = { fg = "text" }
"ui.text.focus" = { bg = "overlay" }
"ui.text.info" = { fg = "subtle" }
"ui.text.directory" = { fg = "iris" }

"ui.virtual.jump-label" = { fg = "love", modifiers = ["bold"] }
"ui.virtual.ruler" = { bg = "overlay" }
"ui.virtual.whitespace" = { fg = "highlight_high" }
"ui.virtual.indent-guide" = { fg = "muted" }
"ui.virtual.inlay-hint" = { fg = "subtle" }

"ui.menu" = { fg = "subtle", bg = "surface" }
"ui.menu.selected" = { fg = "text" }
"ui.menu.scroll" = { fg = "muted", bg = "highlight_med" }

"ui.selection" = { bg = "overlay" }
"ui.selection.primary" = { bg = "highlight_med" }

"ui.cursorline.primary" = { bg = "highlight_low" }
"ui.cursorline.secondary" = { bg = "surface" }

# "warning" = "gold"
# "error" = "love"
# "info" = "foam"
# "hint" = "iris"
"debug" = "rose"

# "diagnostic" = { underline = { color = "subtle", style = "curl" } }
# "diagnostic.hint" = { underline = { color = "iris", style = "curl" } }
# "diagnostic.info" = { underline = { color = "foam", style = "curl" } }
# "diagnostic.warning" = { underline = { color = "gold", style = "curl" } }
# "diagnostic.error" = { underline = { color = "love", style = "curl" } }
"diagnostic.unnecessary" = { modifiers = ["dim"] }
"diagnostic.deprecated" = { modifiers = ["crossed_out"] }
"special" = "rose"

# USER INTERFACE - DIAGNOSTICS
"warning" = { fg = "lemon_zest" } # diagnostics warning (gutter)
"error" = { fg = "ruby_glow" } # diagnostics error (gutter)
"info" = { fg = "sky_blue" } # diagnostics info (gutter)
"hint" = { fg = "walnut_brown" } # diagnostics hint (gutter)
"diagnostic" = { modifiers = [
  "reversed",
] } # diagnostics fallback style (editing area)
"diagnostic.hint" = { fg = "deep_abyss", bg = "walnut_brown" } # diagnostics hint (editing area)
"diagnostic.info" = { fg = "winter_sky", bg = "twilight_blue" } # diagnostics info (editing area)
"diagnostic.warning" = { fg = "winter_sky", bg = "rustic_amber" } # diagnostics warning (editing area)
"diagnostic.error" = { fg = "winter_sky", bg = "rustic_red" } # diagnostics error (editing area)


"attribute" = "iris"

"type" = "foam"
# "type.builtin" = ""

"constructor" = "foam"

"constant" = "foam"
"constant.builtin" = "love"
"constant.builtin.boolean" = "rose"
"constant.character" = "gold"
"constant.character.escape" = "pine"
"constant.numeric" = "gold"
# "constant.numeric.integer" = ""
# "constant.numeric.float" = ""

"string" = "gold"
# "string.regexp" = ""
# "string.special" = ""
# "string.special.path" = ""
# "string.special.url" = ""
# "string.special.symbol" = ""

"comment" = { fg = "muted", modifiers = ["italic"] }
# "comment.line" = ""
# "comment.block" = ""
# "comment.block.documentation" = ""

"variable" = "text"
"variable.builtin" = "love"
"variable.parameter" = "iris"
# "variable.other" = ""
"variable.other.member" = "foam"

"label" = "foam"

"punctuation" = "subtle"
# "punctuation.delimiter" = ""
# "punctuation.bracket" = ""
# "punctuation.special" = ""

"keyword" = "pine"
# "keyword.control" = ""
# "keyword.control.conditional" = ""
# "keyword.control.repeat" = ""
# "keyword.control.import" = ""
# "keyword.control.return" = ""
# "keyword.control.exception" = ""
"keyword.operator" = "subtle"
# "keyword.directive" = ""
# "keyword.function" = ""
# "keyword.storage" = ""
# "keyword.storage.type" = ""
# "keyword.storage.modifier" = ""

"operator" = "subtle"

"function" = "rose"         # maybe pine
"function.builtin" = "love"
# "function.method" = ""
# "function.macro" = ""
# "function.special" = ""

"tag" = "foam"

"namespace" = "text"

"markup.heading.marker" = "muted"
"markup.heading" = { fg = "iris", modifiers = ["bold"] }
"markup.heading.1" = { fg = "iris", modifiers = ["bold"] }
"markup.heading.2" = { fg = "foam", modifiers = ["bold"] }
"markup.heading.3" = { fg = "rose", modifiers = ["bold"] }
"markup.heading.4" = { fg = "gold", modifiers = ["bold"] }
"markup.heading.5" = { fg = "pine", modifiers = ["bold"] }
"markup.heading.6" = { fg = "foam", modifiers = ["bold"] }
# "markup.heading.completion" = ""
# "markup.heading.hover" = ""
"markup.list" = "muted"
# "markup.list.unnumbered" = ""
# "markup.list.numbered" = ""
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link" = "iris"
"markup.link.url" = { fg = "iris", underline = { color = "iris", style = "line" } }
"markup.link.label" = "subtle"
"markup.link.text" = "text"
"markup.quote" = "subtle"
"markup.raw" = "subtle"
# "markup.raw.inline" = {}
# "markup.raw.inline.completion" = {}
# "markup.raw.inline.hover" = {}
# "markup.raw.block" = {}
# "markup.normal" = ""
# "markup.normal.completion" = ""
# "markup.normal.hover" = ""

"diff" = "overlay"
"diff.plus" = "foam"
"diff.minus" = "love"
"diff.delta" = "highlight_high"
# "diff.delta.moved" = ""

[palette]
#Original
base = "#191724"
# base = "#0A090E"
surface = "#1f1d2e"
overlay = "#26233a"
muted = "#6e6a86"
subtle = "#908caa"
text = "#e0def4"
love = "#eb6f92"
love_10 = "#311f30"
gold = "#f6c177"
gold_10 = "#30282c"
rose = "#ebbcba"
rose_10 = "#2f2834"
pine = "#31748f"
pine_10 = "#1a2030"
foam = "#9ccfd8"
foam_10 = "#252937"
iris = "#c4a7e7"
iris_10 = "#2b2539"
highlight_low = "#21202e"
highlight_med = "#403d52"
highlight_high = "#524f67"


# PALETTE USER INTERFACE
deep_abyss = "#080d15"
stormy_night = "#254862"
nightfall_blue = "#1f2937"
midnight_thunder = "#0d1526"
twilight_blue = "#2c5484"
pitch_black = "#000000"
winter_sky = "#f3f4f6"
slate_gray = "#838a97"
blaze_orange = "#ff9000"
lemon_zest = "#ffba00"
leafy_green = "#81be83"
dreamy_blue = "#6eb0ff"
crystal_blue = "#99c7ff"
sky_blue = "#45b1e8"
moonlight_ocean = "#0c1420"
rustic_red = "#540b0c"
ruby_glow = "#fa7970"
walnut_brown = "#987654"
rustic_amber = "#9d5800"
slate_purple = "#d2a8ff"
light_purple = "#7533bd"
deep_purple = "#4c1785"
